[tool.ruff]
line-length = 120
target-version = "py311"
src = ["app/src"]
exclude = ["venv", ".venv", "__pycache__", "migrations", ".ruff_cache"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "A", "C4", "SIM", "T20", "RUF"]
ignore = ["E501", "I001"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-third-party = ["fastapi", "pydantic", "sqlalchemy", "uvicorn", "sqlmodel"]
known-first-party = ["app"]
combine-as-imports = true
force-sort-within-sections = false
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
